apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-service-config
  namespace: apps
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker.infra.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "redisListener"
  RABBITMQ_HOST: "rabbitmq.infra.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  MONGO_HOST: "mongodb.infra.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "kv_database"
