apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace.apps }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
      annotations:
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
      - name: frontend-service
        image: {{ .Values.images.frontendService.repository }}:{{ .Values.images.frontendService.tag }}
        ports:
        - containerPort: 8293
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers }}
        - name: KAFKA_HOST
          value: "kafka-broker.infra.svc.cluster.local"
        - name: SPRING_REDIS_HOST
          value: "redis.infra.svc.cluster.local"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq.infra.svc.cluster.local"
        - name: SPRING_DATA_MONGODB_HOST
          value: "mongodb.infra.svc.cluster.local"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        startupProbe:
          tcpSocket:
            port: 8293
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8293
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8293
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
