apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-service
  namespace: {{ .Values.namespace.apps }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-service
  template:
    metadata:
      labels:
        app: trace-service
      annotations:
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
      - name: trace-service
        image: {{ .Values.images.traceService.repository }}:{{ .Values.images.traceService.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers }}
        - name: KAFKA_GROUP_ID
          value: "trace-service-group"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
