# ------------------------
# Server port
# ------------------------
server.port=8215

# ------------------------
# Kafka Producer Config
# ------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.auto.create.topics.enable=true
spring.kafka.producer.properties.spring.json.add.type.headers=false





spring.kafka.admin.auto-create=true

# Spring Kafka JsonSerializer automatically adds type metadata in headers.
# So producer sends:
# __TypeId__ = com.example.redis_service.dto.RedisResponseEvent
# But your frontend has:
# com.example.frontend.dto.RedisResponseEvent
# Different package → different class →  crash.