apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-service
        image: rajashekarganiger2002/redis-service:v2
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: redis-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
