apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-service
  template:
    metadata:
      labels:
        app: trace-service
    spec:
      containers:
      - name: trace-service
        image: rajashekarganiger2002/trace-service:v2
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker.infra.svc.cluster.local:9092"
        - name: KAFKA_GROUP_ID
          value: "trace-service-group"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
