# ------------------------
# Server port (optional if no web UI)
# ------------------------
server.port=8090

# ------------------------
# Kafka Consumer Config
# ------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=redis-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.auto.create.topics.enable=true

# Optional: topic name
# app.kafka.topic=kv-topic

spring.kafka.consumer.auto-offset-reset=latest







# ----------------------------
# RabbitMQ configuration
# ----------------------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
# Optional if your RabbitMQ requires username/password
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ----------------------------
# Redis configuration
# ----------------------------
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=yourpassword  # uncomment if Redis requires password

# ----------------------------
# MongoDB configuration
# ----------------------------
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=kv_database
# spring.data.mongodb.username=youruser   # if Mongo requires authentication
# spring.data.mongodb.password=yourpass
spring.data.mongodb.auto-index-creation=true




# docker run -d --name mongodb -p 27017:27017 mongo:latest
# docker exec -it mongodb mongosh